all:
  hosts:
    active_asa:
      ansible_host: 1.1.1.1              
    standby_asa:
      ansible_host: 1.1.1.2

      
  vars: 
    ansible_user: "{{ lookup('env', 'ASA_USER') }}"
    ansible_password:  "{{ lookup('env', 'ASA_PASSWORD') }}"
    ansible_network_os: cisco.asa.asa
    ansible_command_timeout: 180'
    wait_seconds: 60